### ISSUE TITLE
舉例不當

### ISSUE THREAD

**Issue by Bobo-alcazar** [ichitenfont/inheritedglyphs#10]
規則一曰：
「一、完全同形字只收錄一次。例如「鋁」既是古代鑄銅金屬，也是現代元素；「份」既指整體裏的一部份、量詞等，也是「彬」字的古代異體。本表不會收錄兩個「鋁」字或兩個「份」字。」
字詞異義，理之固然。言「份」與「份」爲同形字則可，言「鋁」分二字則非。蓋二「份」字理異源；而「鋁」則雖二詞而一字記之也。金屬之「鋁」與元素之「鋁」，皆從金呂聲之字，且其用相孳衍。若「米」之言metre與稻，斷無關係，其字則一。若言姱之「好」與婦好之「好」，則同形字之正也。

**Comment by i-font** [comment]
感謝意見，已修改行文。
