### ISSUE TITLE
亟部件

### ISSUE THREAD

**Issue by dine2014** [ichitenfont/inheritedglyphs#11]
《傳承字形部件檢校表》用深藍色標示從「亻」的寫法，意思是該寫法「符合字理且廣受今天大眾約定俗成」。但是翻遍[國學大師網站上的工具書](http://www.guoxuedashi.com/zidian/4E9F.html)，僅有[字彙](http://www.guoxuedashi.com/kangxi/pic.php?f=zihui&p=85)、[正字通](http://www.guoxuedashi.com/kangxi/pic.php?f=zhengzitong&p=45)從「亻」，絕大多數字典都將其連同上面一筆寫成「丂」（少數和大陸新字形一樣寫成「了」）。同樣、cwTeX 明體、以及日韓舊字形標準也都連同上面一筆寫成「丂」。從「亻」的寫法如何「廣受今天大眾約定俗成」？

**Comment by zoe-the-scribe** [comment]
粗略觀察下，常見系統電腦字體多無統一安排，同一部件在不同字中或從「了」形或從「丂」形，看不到規律。I.Ming 從「人」據字源可謂有理，唯印刷出版物似多從「丂」，見[覆「大宋」本《廣韻》](https://ctext.org/library.pl?if=en&file=77414&page=80). 然而此部件在 I.MingVar 字體從似「丂」字形，與「常見」印刷體同。這種安排或許是字源與習例不能兩全情形下的變通。

**Comment by SyaoranHinata** [comment]
抱歉在同伴提醒後才看到這邊有issue。看來dine2014對我們的推薦形體有些誤會，容我在這裏解釋一下。其實，本來我們正在編撰《形體闡釋表》，詳闡構形理據，解釋選形的考慮。然而百務纏身，人手又極度匱乏，實在需要時間。

推薦形體之選定，最主要的考慮原則有三：一者爲字理。漢字是語素文字（亦稱意音文字，日常通俗層面也稱表意文字），會根據其相應的某個字義來構造文字形體。我們維持漢字構造具有合理構意，能依據既定的造字原理，察見該字的造字意圖和理據，有助維護漢字這套龐大符號的秩序，減少其混亂無章的情況。二者爲約定俗成。漢字是套全球很多人共同使用的符號，我們要是閉門造車，選出甚至生造出乏人認受的形體，只能孤芳自賞，這套推薦形體就失去實用功能，大家不能用它來傳情達意。三者爲美觀設計需求。字形設計，講求點畫清晰，黑白均稱，造型穩妥，視覺平衡。符合這些條件的字形，才會看得舒服，方便我們閱讀。

爲此，我們上下耗了許多精神和時間，從重要字書（字書列表見《檢校表》前言）、印刷字模、照排植字、彫版和木活字古籍裏取樣，比較形體的常見程度，並且在符合約定俗成準則的字形中，衡量它們的字理優劣，檢視有否破壞美觀需求，並綜合各種實際考慮予以取捨。個別傳承字形（傳統字形、舊字形）有多種寫法，編者會說明最符合字理，同時不悖於約定俗成準則的「字理寫法」，以及因美觀需要，在傳承字形書刊等場合中普遍可見的「常見寫法」。所謂約定俗成準則，指該字形能融入在日常生活中，大家看到該字形，就能馬上辨識出來，不會混淆其他字，也不會有錯字之惑。若有需要，我們會透過通訊軟件，在事先已答應參與這調査的朋友中，隨機抽選十位朋友詢問能否辨識該字形，以及會否覺得其寫法有誤。選中的十位朋友必須包含生活在香港、臺灣、中國大陸和海外者。詢問過一個或一組字形後，若要詢問另一個或另一組字形，須重新抽樣。

如果那字形是重要字書、印刷字模、照排植字的取樣中的大多數，我們在《闡釋表》裏會直接說明是取樣結果。如果那字形，不算是大多數，但確實存在，並且能通過上述約定俗成準則的測試，我們在《形體闡釋表》裏會說明是符合約定俗成準則。只要符合這兩項條件中的任何一項（或同時符合兩項），再加上在字理上佔優，該字形在《檢校表》裏都會顯示作「海藍色」（海類），代表它符合字理並獲大家約定俗成認同。當然，也有一些常見寫法，符合這兩項條件的任何一項（或同時符合兩項），那些寫法也很有價值，尤其是在字型設計美觀上也很佔優（這方面我們諮詢了專業字形設計師的意見），但在字理上不及其他入選字形般佔優，我們就標示作「草綠色」（地類）。此外還有一種，是字理上佔優，但不通過這兩項條件的任何一項，我們會標示作「天藍色」（天類）。

就「亟」字而言，《正字通》的寫法（從「亻」）在漢字文字學的字理上，它也能順利通過上述約定俗成準則的測試，因此它在文件中作爲「海類」。《康熙》的寫法（從「ㄅ」）較難看出是「人部件」，相比前述字形，它較容易與「丂部件」相混，使人誤解了其字理，因此它在文件中作爲「地類」。但無論是哪一類，都是我們文件裏承認的字形，我們絕不排斥任何一者。我們明白，每個人心裏都有自己的想法，很難有一套標準是任何人都百份百符合自己的主觀願望的。在《檢校表》內的字，不論是「天、地、海」的哪一種，都是我們承認的字，這方便也讓字型設計師的作業，也爲過去已有多套標準並存的舊字形保留包容空間——如果閣下一直留意古籍和過往的字形，應該知道傳承字形本身過去就有多套標準，比如《正字通》字頭是一種，《康熙》字頭是一種，《大漢和》字頭是一種等等。它們彼此之間都大同卻小異（大約是八、九成以上相同，僅有少量相異，但的確有相異），然而它們都的確是傳承字形標準。而這些差異，不一定簡單地說純粹從眾就可以解決，純粹從眾的結果，可以造成部件內部的不必要矛盾，或近似部件間的不必要衝突。因此，我們在表內收錄的形體，有必要同時考慮漢字文字學這專門學術上的理據。但我們也沒有否定從眾的傳承字形，在表中也盡量吸納。甚至即使表裏未必能悉數吸納，我們也多番說明，希望大家對各種傳承字形能盡量包容而不是排斥。

在這裏，我希望dine2014能明白，我們絕無貶低或排斥「從『ㄅ』的『亟』」，沒有認爲「從『ㄅ』的『亟』」不夠約定俗成。同時，也希望dine2014不要排斥「從『亻』的『亟』」，不要聲稱「從『亻』的『亟』」並不是傳承字形。

**Comment by dine2014** [comment]
感謝回覆，我誤以爲「廣受今天大眾約定俗成」是指「最大公約數字形」（即閣下說的「從眾」）。

**Comment by dine2014** [comment]
不過《字彙》、《正字通》、《經典文字辨證書》的「亟」字頭，其「亻」部件上下緊貼「𠄠」，撇筆稍微靠左，且豎筆略有弧度，因此辨識度較高，不知能否用於一點明體的造型。另外，「保」的右下角似乎不作頓點也能與「木」區分，作了反而有點像台灣新字形般肌肉萎縮。

**Comment by i-font** [comment]
> 不過《字彙》、《正字通》、《經典文字辨證書》的「亟」字頭，其「亻」部件上下緊貼「𠄠」，撇筆稍微靠左，且豎筆略有弧度，因此辨識度較高，不知能否用於一點明體的造型。

如此輕微的差異，對字理沒有影響，我們並不視爲不同形狀，視爲只是設計風格差異，取決於該字型本身的風格和設計師的喜好而已。「一點明體」來自「IPA明朝體」，本身筆畫比較僵直，使其𡱒幕顯示較果較好，未必容易作你所說的調整。但如果像蒙納黑體或宋體，偏向人文風且筆畫比較帶弧度的，相信依其本身風格自然地設計，就能夠造出你所說的那種形狀。

> 另外，「保」的右下角似乎不作頓點也能與「木」區分。

不知你指的是像下圖中的哪種字形？不過，無論是哪一種，我們也一樣，皆視爲只是設計風格差異，取決於該字型本身的風格和設計師的喜好而已。並不視爲不同形狀。

![保](https://user-images.githubusercontent.com/24702034/97111954-a2a24a00-171c-11eb-805e-b943d240b9e6.png)

**Comment by dine2014** [comment]
「保」的話，個人認爲 3 和 4 都比較美觀，1 和 2 似乎違反《檢校表》表三「明體、黑體等印刷字型，如無必要，毋須避讓。尤其是撇與捺對稱，或捺筆延伸空間充足時，更不宜避讓」的建議。至於「亟」，可能是我多慮了。

**Comment by i-font** [comment]
上方的字圖，我都是憑閣下所說的一些蛛絲馬跡瞎猜的。
對於「一點明體」（及其來源「IPA明朝體」）這種較硬朗現代，較省掉各種裝飾和人文溫度，着重屏顯簡約的字型來說，圖3和4對有些設計朋友來說，會有「在哪兒懸掛這捺筆都不太對」（指捺筆的起點）的奇怪感覺。好像現在那一捺，感覺上會比撇筆更爲靠近中豎。不過要是把開始位置右移，看起來卻好像會比撇筆萎縮。不過如果是較爲溫潤的明體或黑體，比如借用「游Gothic體」來設計，其效果可能會很不一樣。因此這方面，我們也給予設計師空間，取決於該字型本身的風格和設計師的喜好，不視爲不同形狀。

**Comment by dine2014** [comment]
抱歉，我之前誤以爲「保」字 1 和 2 的造型違反《檢校表》表三「尤其是撇與捺對稱，或捺筆延伸空間充足時，更不宜避讓」的建議，但康熙字典的「茶」的「小木形」亦以頓點結尾。至於「亟」，可能是我個人不習慣吧，「亻」的上方如果能夠緊貼那一橫，與從「ㄅ」的康熙寫法更相似。但如果其他人能習慣一點明體的寫法也沒問題。

**Comment by SyaoranHinata** [comment]
請dine2014閣下不要再誤讀了。把一句或一段說話，抽空本來的背景和場景，還割斷前後文脈，大概只會得出曲解。尤其是在閣下第一次曲解，我跟閣下解釋後，閣下竟然刪掉第一次曲解的原文，然後來這裏作出更變本加厲的曲解，恕我直言，竊以爲這不是友善溝通的表現。

[本來那段對話](https://github.com/lxgw/LxgwWenkaiTC/issues/7)的語境，是在Klee One原字型本身已符合日標，也有其他人改作成臺標版等不同字形版本下，試作霞鶩文楷繁體版的Lxgw兄開這個issue出來問大家意見，看看是否「有必要完全遵循《傳承字形部件檢校表》」，是否盡力依《檢校表》推薦字形來製作這版本。Lxgw兄會這樣問，是覺得盡力依推薦字形的話修改頗多，如果不盡力依，就少一些修改，省力一些。但我指出，有去盡力依的需求，有以字理字源作依歸來製作字形的需求。在字理字源上，如果兩個形似部件明明有方法、有能力可作區分，卻不區分，這確是被「差不多」主義影響了，犧牲了重視字理字源的使用者之權益，是重視字理字源的使用者所不希望的事。我的意思就是如此。

但我沒有反對有日標字形存在，也不是要壓下日標字形的需求，不是要觸日標字形愛好者得逆鱗。更絕對沒有在下所指控的把『遵循日韓舊字形標準的字型製作者打成「差不多先生」』。如果我眞的有這意思，我怎麼對本身遵從了日標的Klee One原字型沒有半點兒批評？要是閣下第一次曲解，我還可以體諒是誤會。但閣下在我解釋以後，在我說得清清楚楚，並沒有說以日標或其他字形製作的就是閣下所指控的『考慮不周全』或『品質有問題』，閣下卻先自刪再到這裏發表更嚴重的曲解，請恕我感到閣下並不是要理性溝通。

我知道dine2014閣下一向對《檢校表》的推薦字形有一些不認同的地方，想那些字形從《檢校表》中消失，以閣下心目中的來取代。但《檢校表》的推薦形體，實在有其需求。我們只是堅持希望能有盡力依從《檢校表》的推薦形體的字型，但從來沒反對過同時有其他字形可供選擇，也沒有批評過提供不同選擇的人。我只可以再次請dine2014閣下不要再誤讀，更不要斷我章取我義，拜託。不然的話，我也無法回應。希望以後的溝通，能回到理性的對話上。謝謝！

P.S. 同時也呼籲一些本來就想反對傳承字形的網民，要是大家都喜歡斷章取義式的擷圖，放大他人的誤讀或曲解，完全無視我原來說什麼，企圖值此來在QQ群組或者什麼地方公審我的話，其實大家公審的並不是我，只是稻草人。而那個稻草人的主張，根本就不是我的主張。要是大家眞的想討論有益，但凡可以用理據去說明的，請回到理據上。私怨無益，單向私怨更無益。謝謝！

**Comment by hfhchan** [comment]
> 另一方面卻把嚴格遵循日韓舊字形標準的字型製作者打成「差不多先生」

> 就像你說，不少非臺標字形的「辛部件」、「音部件」等用豎點。有什麼問題呢？字理上，「辛」的上方不是「立」。能不與「立」混同的話，就不應該混同。「辛」的首筆作短橫（楷體的話可以作側點，但不要作豎點，這點在《筆畫表》裏已詳述），有字理、學術依據，在漢字設計的美學要求上也不相悖，那麼，個人就不希望做差不多先生。

這個批評頂盡只是涉及日標的選型而已，哪裏是抨擊依日標製作字形的字體製作者？

日標常用字的選形本身就是為了方便教育而設，有不同考量。本身各國及地區之標準形，從字理角度，各有優劣。日標常用字選用「𠮟」而不採用「叱」，明顯更符合字理，這個選型其他地區都沒有日標般符合字理。

另一方面，日標因為字體改革的歷史問題，導致日標經常出現同一個部件同一個位置採用不同形體的情況。這個問題這裏我不詳述了。

大家客觀理性哋評論字形的優劣有什麼問題？隨着印刷體的發展，字書一直演變出更符合字源的寫法，有些寫法流傳開去，有些沒有。認為「能分則分」，認為「不分不嚴謹」，怎麼就理解成了是在打壓別人呢？

**Comment by SyaoranHinata** [comment]
P.S. 同時也呼籲一些本來就想反對傳承字形的網民，要是大家都喜歡斷章取義式的擷圖，放大他人的誤讀或曲解，無視我原來說什麼、本來是什麼意思，企圖借此來在QQ群組或者什麼地方公審我的話，其實大家公審的並不是我，只是稻草人。而那個稻草人的主張，根本就不是我的主張。要是大家眞的想有益地討論，但凡可以用理據去說明的，請回到理據上。私怨無益，單向私怨更無益。謝謝！

**Comment by dine2014** [comment]
對不起，我錯誤地把「就像你說，不少非臺標字形……」的「字形」(glyph) 理解成了「字型」(font)，因爲這句話對應的是上面的「很多非臺標的繁體中文字型」。如果不把「字形」視作「字型」的筆誤，「就像你說」四個字就會落空。至於「做差不多先生」，可能是詞義較字面義發生了弱化，沒有針對人的意思。

P.S. 我説的日韓舊字形標準並不包含日標的新字形部份。
