### ISSUE TITLE
《傳承字形推薦形體表》部分 Unicode 碼有誤

### ISSUE THREAD

**Issue by dine2014** [ichitenfont/inheritedglyphs#13]
《傳承字形推薦形體表》所列部分漢字 Unicode 碼有誤。其中「勖」來自表一，其餘來自表三。

漢字|正確 Unicode 碼|錯誤 Unicode 碼|錯誤 Unicode 碼對應漢字
-|-|-|-
勖|52D6|4E03|七
䱽|4C7D|4C70|䱰
咓|5493|9E75|鹵
芦|82A6|9ECD|黍
嗬|55EC|4E95|井
碱|78B1|4EC7|仇
䥑|4951|4ECB|介
歒|6B52|4E9F|亟
麄|9E84|5FFF|忿
埪|57EA|4F84|侄

**Comment by SyaoranHinata** [comment]
感謝回報，我們將會更正。
