### ISSUE TITLE
《傳承字形推薦形體表》部分 Big5 碼有誤

### ISSUE THREAD

**Issue by dine2014** [ichitenfont/inheritedglyphs#14]
查閲 [Unihan Database](http://www.unicode.org/charts/unihan.html)，發現《傳承字形推薦形體表》所列部分漢字 Big5 碼有誤。

漢字|Unihan 所載 Big5 碼|本表所列 Big5 碼|本表所列 Big5 碼對應漢字
-|-|-|-
不|A4A3|A4A5|丰
丐|A4A2|A4A4|中
丑|A4A1|A4A3|不
中|A4A4|A4A6|丹
丰|A4A5|A4A7|之
丹|A4A6|A4A8|尹
之|A4A7|A4A9|予
勖|D46D|A443|七
孭|未載|A45F|于
綉|未載|F9D7|銹
咓|未載|B3BF|鹵
秄|未載|A4B6|介
萘|未載|9FC6|莾
袜|未載|A8CA|京
㞗|未載|A6EB|亨
歒|未載|AB45|亟
舚|未載|CA65|佘
轜|未載|CA5E|体
𠸏|未載|CA69|佡
𥑮|未載|CBC8|侒
埪|未載|CBBB|侄
𨃰|未載|A460|亡
攴|未載|A4AD|五

**Comment by dine2014** [comment]
知乎《[關於傳承字形的謬說與事實](https://zhuanlan.zhihu.com/p/260646301)》裏的截圖亦有誤，特別是左下方的「之」與右上角的「予」Big5 碼相同。

**Comment by SyaoranHinata** [comment]
感謝回報，我們將會更正。
