### ISSUE TITLE
《檢校表》部件舉例例字重出

### ISSUE THREAD

**Issue by dine2014** [ichitenfont/inheritedglyphs#16]
《傳承字形部件檢校表》表一「羽部件」云：

> 例字如：栩、詡、翁、嗡、翕、噏、扇、煽、𦐇、塌、翰、瀚、翦、翥、翡、**翎**、翊、翵、𦭳、羾、翂、翃、翅、**翎**。

此處「翎」字似重出。

表二「卂、丮、凡之別」下「卂部件」云：

> 即「迅、訊、汛、扟、**阠**、蝨、𧈲、籸、軐、**阠**、䒖、䭀、𣥇、𤣲(U+248F2、U+248ED)」等

此處「阠」字亦似重出。

**Comment by dine2014** [comment]
此外，表二「舌（首筆橫）部件」字頭

> 舌舐舓舔舑舕舚甜恬**栝**銛絬**栝**…

「栝」字似重出。

**Comment by dine2014** [comment]
題外話：《推薦形體表》各章結構類似，閲讀時往往不知自己在哪一章（即「表幾」），也無法快速跳到表後的注釋。建議添加頁眉、PDF書籤、超鏈接等設施，方便瀏覽。

**Comment by dine2014** [comment]
此外，《檢校表》表二下的小標題「市、市之別」疑爲「市、巿之別」之筆誤。

**Comment by SyaoranHinata** [comment]
重出例字和「市、巿之別」皆已更正。
《推薦形體表》各表已上頁眉註明是何表。
《推薦形體表》大字下的註釋數字已加上超連結。
