### ISSUE TITLE
只有部訂標準能夠代表正體字

### ISSUE THREAD

**Issue by uoo-wsiq-bn** [ichitenfont/inheritedglyphs#18]
你的字表說成是標準，可是我一看，許多字都不像，例如肉部要點挑才對，你們寫的都不正確，寫成兩橫就變成月，不是標準。

然後你們說什麼傳承字形，這是無聊爛透的。你們在開發的字體又不是簡殘体字，難道不是台灣人作為主要使用群嗎？你們沒有把部訂的字形做出來，這樣不能講？

身為台灣老百姓，我是中華民國國字標準字體派。只有部訂的標準才可以代表正體字。所以我希望能有台灣字形有何不可？為什麼你們寫錯字，還要把自己說成是標準？

**Comment by hfhchan** [comment]
你這裏根本是捩橫折曲，完全無視台灣教育部篡改繁體字印刷的標準形的事實。

另外繁體字不只是台灣人在用。繁體字也不是台灣教育部的財產。人民的存在也不是要支配某個政府部門。現在不是威權統治時代，拜托做人不要那麼法西斯。

你希望依國字標準是你的事，問題是電腦廠商把明明符合字源字理、流存下來的傳統寫法的字體都換掉，這是剝奪了其他使用者的權利。

現在電腦系統預設的字體就是國字標準，你還抱怨什麼？抱怨別人看法和你不一樣？覺得政府標準至高無尚，別人不能批評？

你跑過來質疑我們的批評，原因就離不開「政府是對的」，你不感到羞恥嗎？

**Comment by aikahiiragi** [comment]
戴定頭盔，這一層樓的回覆只是我的個人吐嘈，不代表組織。

看到頂樓的言論，基本上又是一個死太監，不對，又是一個台標盲目死忠。

首先，漢字印刷體有了許多前，未有中華民國教育部時就已經有。教育部頂多是訂了一個小學生測驗默書的標準，所謂的“中華民國國字標準字體”這名字根本過大，

**Comment by SyaoranHinata** [comment]
uoo-wsiq-bn 閣下的發言，證明有不少臺灣朋友仍然對漢字無知，只以自己的幻想來理解漢字，令人感到很遺憾。

閣下提到「月」與「肉」，其實傳承字形的表現，遠比「臺標」（敎育部標準字體）嚴謹得多。

「月、肉、舟、円」五個部件，傳承字形都有所區分。如下圖所示：
![image](https://user-images.githubusercontent.com/8178284/156118671-4395c330-384e-4226-9cf5-5a13c03f2666.png)

而且這區分方法，是遵從在文字學學術上的前賢說法，你翻《說文》、《康熙》、《大漢和》、《辭海》等等權威標準都是如此（下圖爲《康熙》裏的「辨似」說明）。我們《檢校表》裏的「肉部件」，正是這種符合字理的傳統字形。
![image](https://user-images.githubusercontent.com/8178284/156118835-0a62d334-203e-461f-988c-85373724d29f.png)

因此，若眞的要說字理、字源，當用傳承字形。而且傳承字形在區分部件的同時，還顧及美觀所需，保持明體、黑體等印版字的端正工整，「肉」旁的設計並不會鬆散無架。

「臺標」的手冊雖然開口六書閉口考據，卻只區分「月」與「肉」，把「舟、円」等本來不相混的部件強行混同，廢止其傳承寫法。這根本是掛羊頭賣狗肉。

如果符合字理，有歷史依據，獲學界認可，也在日常生活中司空見慣的傳承字形，要被 uoo-wsiq-bn 閣下如此貶斥，那麼，問題是出來古往今來這麼多人（當中包括漢字文字學界擧足輕重的學者）身上，還是閣下的認知上呢？

其實，傳統字形不但有多年字匠的美學沉積，也更符合字理字源。臺灣敎育部門如果眞的要強調字源的話，爲甚麼反而摒棄更符合字理字源的形體，要強行「認楷作母」改造傳承字形，甚至錯誤地敎育學生，把正確形體當成是「錯字」、「無法用在敎科書上」呢？除非他們宣稱的其實是藉口，否則我眞的百思不得其解。

P. S. 日常層面用字，有不同的功能和選擇，我們並不主張說不區分的寫法就是「錯字」，沒有說「臺標」就是「錯字」。我只是說：一、大家亦應有權方便地選擇有所區分的形體。二、若要說六書字理，當然應以區分者爲準，否則有騙人之嫌。
而臺標推廣時的實際情況，以及臺標支持者的行爲，皆無視他人的選擇權，並且把臺標以外的寫法都稱作「錯字」，獨奉臺標。這些都是不能接受的。

**Comment by SyaoranHinata** [comment]
還有一點，當年推出「敎育部標準字形」，其實是以官話強力壓下來，輾平、取替臺灣原來語言生境和文化（即打壓「方言」政策）的附帶產物。它的釐定方法也是不顧臺灣本來的印刷傳統，即使在臺灣內外的學術界、書法界和漢字設計者，也廣受批評。只是它的推行，並沒有打壓「方言」政策般強力，只用於學童敎科書。

上方佟兄提到「轉型正義」，我也深有同感。本來，如果重視臺灣本土，重視轉型正義，就應該把「敎育部標準字形」的地位放輕，讓傳承字形回復原有的生境、空間、選擇權，在敎育上也不宜偏廢。偏偏極度諷刺的是，好些喊着臺灣本土、轉型正義的臺灣人，就把「敎育部標準字形」高擧到一個強力壓下來的位置，用它來輾平、取替原有的字形生境，當中好些這樣的人進入了IT公司或組織，濫用他們的權力強迫使用者只能使用敎育部字形，把學童敎科書以外，各種敎育部都沒有希望用敎標的場合，都變成只能用敎標的，使用者無從選擇的處境，跟當年「推官滅『方』」的霸權嘴臉一模一樣。

**Comment by i-font** [comment]
《傳承字形部件檢校表》的附錄〈關於傳承字形的謬說與事實〉，已有一些有關樓主言論的解說，有勞樓主 uoo-wsiq-bn 閣下多點運用眼睛和腦袋，先行細閱，再多思考。

爲方便樓主，且摘錄出來，如下：

//
甚麼是傳承字形，甚麼是本表中的傳承字形推薦形體，甚麼傳承字形標準等等，我們已在本表的前言中清楚闡明。可是，網上仍有一些人，扭曲了這些詞彙的原來定義。當中有些是因爲不清楚而誤解誤說，有些卻因另有目的而故意歪曲。爲方便大眾明瞭，我們謹於這裏輯錄這些謬誤，並指出其訛謬之處，闡明事實。

**謬說：**聲稱傳承字形「沒有標準」，聲稱重要字書標準、學界標準（如《康熙》字頭字形、《大漢和》字頭字形等）並不是「標準」，無人會理會。

**事實：**「標準」者，《現代漢語詞典》釋爲：「①衡量事物的準則。②本身合於準則，可供同類事物比較核對的事物。」據此，但凡對各字寫法有清楚規定或定樣，使它有章可循者，都是字形標準。因此，一部權威字典的字頭，本身就是一套標準。「《康熙》字頭」是一套標準，「《大漢和》字頭」又是一套標準。這是漢字文字學界的入門級常識。上述例子都是具有學術權威的傳承字形標準，在學界內外，都有許多人重視。在本表面世前，傳承字形就已經有好些重要標準。無論立場如何，都應當承認這些客觀事實。
根據我們的接觸經驗，持此謬說的人，往往是故意曲解「標準」的定義，將它扭曲成只有「政權確立」或「某些國際組織背書」才算「標準」。他們藉此手段來高擧某些政權的標準字形，並同時排斥傳承字形。這是偷換概念的卑劣詭辯，違反理性討論的底線。同時，只懂看一個「標準」是否由政權或國際組織確立，不理會該範疇的本科學術知識，等於搞霸權、威權崇拜，言行何其反智。
而且，有不少說出此番謬論的人，身份往往是軟件工程師、前端工程師、程式設計師、萬維網聯盟專家、軟件開發者等資訊科技界人士。他們的學歷跟漢字文字學無涉，發言內容反映了他們對學術的無知，卻往往以高高在上的姿態發佈此等顚黑倒白的論述。這是以無知打倒有知的反學術愚行。
如果要選出一個代表傳承字形的標準，以免有多個標準無所適從，我們很推薦大家選擇本表推薦形體。與過往標準相比，本表推薦形體的考據更細緻，採樣更現代，在學術理據和約定俗成兩方面都更優勝。但這不代表傳承字形在本表面世前並無標準。聲稱「傳承字形沒有標準」的人，無疑是指鹿爲馬。

**謬說：**認爲印刷字形來自楷體，「認楷作母」是正確的做法。

**事實：**印刷字形並非完全直接承繼自楷書。與手寫楷體相比，印刷字形本身就有着不同需求和特點，它能做到點畫分明，字形顯示得比手寫字更鉅細無遺，所以它不但不是直接沿襲楷書，更在與字理相關的一些筆畫上，做得比楷書更貼近字源。印刷字形的美學需求更與楷書書法大異其趣。直接以楷書寫法去論印刷字形，要求印刷字形亦步亦趨地被楷書寫法牽着鼻子走，即所謂「認楷作母」，是本質上的錯誤，混淆了不同書體或字型的特質。
//
