### ISSUE TITLE
《傳承字形部件檢校表》表二“舌部件”下筆誤

### ISSUE THREAD

**Issue by dine2014** [ichitenfont/inheritedglyphs#2]
《傳承字形部件檢校表》表二〝舌部件〟下，字源爲「𠯑」的「舌」對比了「舌」（首筆作撇）和「𠯑」兩種寫法，但是最後說〝故今不取「舌」（首筆作撇）形〟，當爲〝故今取「舌」（首筆作撇）形〟或〝故今不取「𠯑」形〟之誤？

**Comment by SyaoranHinata** [comment]
感謝指正！應作『故今不取「⿱氏口」形』才對。日後將更正。^^
