### ISSUE TITLE
关于撇点的疑问

### ISSUE THREAD

**Issue by lef-est** [ichitenfont/inheritedglyphs#20]
我在文档中搜索“為撇點”时，发现这个笔画在各部件的参考字形中看起来像是两笔，出头很多，甚至到了“怎么看都不像一笔”的程度（读了好几遍说明文字中的“第x笔应为…”，反复数笔画，然后看到附录一中撇点和直撇点确实是很明确的一笔，我才敢确定”即使看起来是那个样子，果然还是一笔“，然后疑惑为什么贵组使用这种初看上去不太符合描述和附录的字形作为参考字形）。

最为明显的可能是系部件。我能理解”和撇挑做出区分“的需求，可是只要笔画转折后是向下或平行，不出头并不会变成撇挑。字理上，出头的写法似乎也不占优。从美观考虑，参考字形第三笔撇的部分止于正中，而点的部分有”一“的长度，更显得像是断开而且让横笔非常瞩目，让这个字的这一区空间像是被截掉了一部分或者说有些萎缩。对于复杂的字，可能两种字形差别不大，但有时还是挺明显的（尤其是系部字），比如”繁“一眼看去下面像是”木“，那一横实在太抢眼球。

我并不懂传承字形（用简体字发问也是怕用错旧字形带偏讨论），只是好奇为什么。这个repo好像没有开讨论区，所以抱歉只能发到issue来。

**Comment by aikahiiragi** [comment]
這應該是設計美學需求吧，如夥折的位置不能出頭（露芒）太多，那麼撇和點的斜度需要向橫發展，使折的位置向左移，不然的話折的位置會偏右使左邊出現許多白色空間。但如果這樣做，改變筆畫斜度後，也會讓字形變得不夠平衡。自己極不專業地在字型維基上班門弄斧了一下如下：

通行的常見明體：
![image](https://user-images.githubusercontent.com/37748071/174271206-2000b25b-f402-48b4-a1cd-0df8549db20d.png)

讓它折筆位置不露芒：
![image](https://user-images.githubusercontent.com/37748071/174271680-eccc77d4-fa63-4a3d-ade1-110db0f6ae44.png)

讓折的位置左移，改變筆畫斜度後：
![image](https://user-images.githubusercontent.com/37748071/174271905-a5cdfa26-89ac-440e-8071-8ec3a80d326a.png)

第2和第3幅的字形都變醜了，所以字型製作師還是會堅持第1幅的傳統做法吧。

**Comment by lef-est** [comment]
那就是主观问题了😂 我觉得1和3各有各的丑，但3再调整一下似乎能比1好看（比如第二笔撇点现在靠近撇挑，可以再平稳一点，也可出一点锋）因为在我看来1的笔画不够匀称，才使“繁”下部看起来像木。而出头的量几乎快1:1，比什么撇点撇挑间的差距要显眼多了，和字理相背到我都不知道怎么掩护。在避免撇挑上，字形表尊崇字理，而我看其他部件里也有“这个要出头” “这个不能出头”等指示，唯独这个部件，感觉好突兀😂

**Comment by SyaoranHinata** [comment]
樓主你好。這種折筆是否突出來的問題，在《檢校表》中是「露芒」而不是「出頭」。整份檢校表中，並沒有使用「出頭」一詞。而露芒與否，或者露芒的明顯程度，主要是關係到設計造型美學方面，跟字理不怎麼相關。

字理者，是指漢字的構形理據，一般來說是以六書中的四體來說明。當中的會意、形聲，關係到兩國或以上的部件怎麼組在一起，組在一起的背後有什麼理據，跟個別一個部件有沒有露芒無關。至於象形、指事，在隸楷以來，因現代筆畫化，本已抽象，難以像甲骨金文般眞正的「畫成其物，隨體詰詘」，筆畫只要能投射過去象形之形體，不跟別的漢字或部件混淆，即具備字理。在此條件下，同樣用現代筆畫化組成，無論是用一個相連的複合筆畫，還是用斷開的兩筆，其實並不影響其投射所象形事件之功能。

以樓主所擧的「糸」部件來說，它的甲金篆形像一束絲線，末端（或首端，又或首尾兩端）有線緒。像束絲之形已是它的字理。到了隸楷，哪怕我們拆開所有複合筆畫，以「撇、點、撇、挑、點、豎、撇、點」八筆去書寫，又或者作行草連筆，整個字只用一筆過寫出來，或者只分作兩三筆都好，所表達的，都是投射過去象形之形體。它們在字理上，不算得有明顯的優劣之分。

既然不怎麼影響字理，一套字形實際上到底露不露芒，或者露多少，就只是設計問題，這方面我們把空間留給設計師。《檢校表》的〈表三：不視作部件區別之差異〉中，列出了若干只視爲設計風格差異，不視作部件差異，無礙字理之情況。當中第一項就是「折筆的處理」，說明了「複合筆畫中的折，折角處露芒與否，只視爲設計風格差異。」

事實上，對漢字造形設計來說，把這個選擇留給設計師，讓他們製作不同風格的字型時有這取捨自由，是有必要的。不同風格的字型，對於漢字的中宮、重心、筆畫架構，以及由筆畫間出來的白色空間之平衡，都有不同的需求。《檢校表》使用的是「一點明體」，是追求現代閱讀的平衡感、比較幾何化的明體。其折筆位置是否可以露芒，往往對字形平衡影響好大。以我們一位朋友製作的下圖爲例：

![image](https://user-images.githubusercontent.com/8178284/178074411-267c2137-99e0-408b-906d-54d4386979e9.png)

像圖中的例子，右方的「至」字是禁止露芒的，誰都可以看到在空間分配上是無法平衡的，左邊的白色空間總會太小，內部的白色空間總會太闊。相反，只要容許露芒，例如左方的「至」字一般，就可以大大改善白色空間的平衡。

Windows系統以細明體作系統字型，細明體本來基於日本的本蘭明朝體來仿製，其實也有跟「一點明體」相類同的設計美觀需求。然而，自從本來視覺還好的、使用傳承字形舊版細明體，被微軟強制改成使用臺敎標字形新版細明體後，能否露芒就不再是設計師的自由，臺敎對此有無視設計美觀需求的規定，結果各方人士都認爲字形醜了這麼多。

其實，以樓主的發言來看，應該是不習慣正體（繁體）中文的環境，因此看到一些與習慣不同、卻未必預料它會有差異的部件時，就會激起陌生感，使樓主未必很接受甚或覺得會誤認。「糸」字若非放在左旁，以主流的識字敎育來說，並不視作有繁簡差異的，但在傳統印刷字的世界中，這部件的主流造型確實跟簡體習慣的新字形不同。

爲免我們受偏見影響，看到樓主的留言後，我們除了諮詢了專業的字型設計師，也隨機抽了十位習慣使用正體（繁體）字的朋友，他們全都覺得傳統露芒的「糸」部件比較美觀。同時，我們也覆檢過《校檢表》主要取樣的來源，發現從中看到的「糸」部件絕大多數都是露芒的，而且露芒的程度也是跟「一點明體」相似的。要刻意不露芒的印刷字，反而非常少。

希望能解答樓主的問題，謝謝。
