### ISSUE TITLE
〈傳承字形部件檢校表II——近形須區分部件〉有誤

### ISSUE THREAD

**Issue by univerplex** [ichitenfont/inheritedglyphs#22]
〈傳承字形部件檢校表II——近形須區分部件〉（component_of_recom_inherited_glyphs-1.35.pdf）中，
「市、巿之別」條誤作「市、『市』之別」，望更正。 
![image](https://user-images.githubusercontent.com/55911276/183668229-76185e44-e950-4a4a-9d31-0c6afb141b03.png)

**Comment by i-font** [comment]
這問題我們早前已發現，將會在下一版更正，謝謝。
