### ISSUE TITLE
關於「又」及其相關郶件

### ISSUE THREAD

**Issue by univerplex** [ichitenfont/inheritedglyphs#23]
竊以爲「又」可从提捺併開口，更合乎字厡且有助於辧識「又」郶件之變形（**更吏史攵父丈祭**……盡从提捺，从斜提捺者唯又郶字），別之以**文乂爻夂交鳮**……等𫟋「又」毫毋干係諸字
例「攴」如圖
![image](https://user-images.githubusercontent.com/55911276/183687156-4ff565d3-7610-4842-9c4e-79e4187c0353.png)

**Comment by i-font** [comment]
我們在《檢校表》中已說明：

> 傳承字形左上角可開口，也可不開。這字篆作「又」，像三根手指，字源上開口與初形較貼近，但即使不開口亦不與別的部件相混，取不開口者比較適應明體造型美觀。例字如：友、苃、及、隻、雙、欆、取、支、技、攴、敲、受、授、叉、扠、衩、㕚、蚤、搔、爰、援、暖、反、坂、報、服、㞋、赧。
避讓時，捺變作點後，左上宜開口，寫作「ㄡ」，以免使交點嚴重側向右上角，失去平衡。例子如：双、叒、桑、叕、啜、𢼅、𤔔、㓟、寇、頍、辤、鳮。
至於捺筆提筆處的飾筆，只屬美觀裝飾，並不影響字理，有無皆可，並不視作部件差異。

我們的選形原則，是從傳承明體中，盡力挑選最符合字理、同時不悖於約定俗成準則的寫法，兼顧美觀設計需求。希望能明白，謝謝。
