### ISSUE TITLE
關於「鬯」及其相頪郶件

### ISSUE THREAD

**Issue by univerplex** [ichitenfont/inheritedglyphs#24]
關於「鬯」及其相頪郶件，其下「匕」形可攷慮作「厶」形，如圖示
![image](https://user-images.githubusercontent.com/55911276/183693378-96f3b8ac-4b4f-42d2-8d14-1ffa6f9575b4.png)
![image](https://user-images.githubusercontent.com/55911276/183692390-cdbc9e3c-c6ed-462b-a341-57821c9d63b0.png)
「鬱」
![image](https://user-images.githubusercontent.com/55911276/183694396-5ae1d856-1d28-40ee-953e-3cda34f25628.png)

**Comment by i-font** [comment]
以區分部件來說，「厶」形本身已有許多用途，再增加其負擔不見得有助彰顯字理。
以約定俗成來說，除了「皀」的隸定也作「㿝」。「鬯」似乎不怎麼見這形狀，也似乎有違約定俗成原則。

我們的選形原則，是從傳承明體中，盡力挑選最符合字理、同時不悖於約定俗成準則的寫法，兼顧美觀設計需求。希望能明白，謝謝。
