### ISSUE TITLE
關於「人」構件變形旳一些建議

### ISSUE THREAD

**Issue by univerplex** [ichitenfont/inheritedglyphs#25]
如「并」可作
![image](https://user-images.githubusercontent.com/55911276/183697448-cb4f5920-f9e4-4e1d-8f64-cae9ad7c5a81.png)
及「眾」可作
![image](https://user-images.githubusercontent.com/55911276/183697201-0f095cd8-3621-4580-9fc2-59a40d111a1e.png)
或
![image](https://user-images.githubusercontent.com/55911276/183700798-04bdfa58-e589-41f7-8096-f445c4279af6.png)

**Comment by univerplex** [comment]
> 如「并」可作 ![image](https://user-images.githubusercontent.com/55911276/183697448-cb4f5920-f9e4-4e1d-8f64-cae9ad7c5a81.png) 及「眾」可作 ![image](https://user-images.githubusercontent.com/55911276/183697201-0f095cd8-3621-4580-9fc2-59a40d111a1e.png) 或 ![image](https://user-images.githubusercontent.com/55911276/183700798-04bdfa58-e589-41f7-8096-f445c4279af6.png)

眾从目从㐺，「㐺」三人當齊高爲宜，爲唐宋印刷字型所本

**Comment by i-font** [comment]
我們的選形原則，是從傳承明體中，盡力挑選最符合字理、同時不悖於約定俗成準則的寫法，兼顧美觀設計需求。希望能明白，謝謝。
