### ISSUE TITLE
關於「邑」郶旳建議

### ISSUE THREAD

**Issue by univerplex** [ichitenfont/inheritedglyphs#26]
「邑」「𨙨」「色」諸字不必封口𫟋「巴」相溷，作
![image](https://user-images.githubusercontent.com/55911276/183737382-52064148-a31c-42bf-b51e-4ac0c1ea9f69.png)；
「邑」作右邑傍旹可變形如
![image](https://user-images.githubusercontent.com/55911276/183737831-6bf29e08-ccba-43a5-9dba-9e2835f0b61e.png)右側，
以𫟋左阜傍（變形爲阝）相別。

**Comment by i-font** [comment]
我們的選形原則，是從傳承明體中，盡力挑選最符合字理、同時不悖於約定俗成準則的寫法，兼顧美觀設計需求。希望能明白，謝謝。
