### ISSUE TITLE
「亂」、「辭」部件

### ISSUE THREAD

**Issue by mondain-dev** [ichitenfont/inheritedglyphs#27]
請教傳承字形對「亂」、「辭」左半部件，即：今通行各字形兩字左半 vs U+022ff3 "𢿳"(IPA/一點明體)左半，是否有取捨？1919年官話和合本似乎多從後者，1915年版辭源(正編)字頭多從前者，“亂”字正文字形多從後者。

官話和合本 (1919):
![官話和合本 (1919)](https://user-images.githubusercontent.com/8684843/188044631-67e7dc79-4df3-4cec-ae5f-70d85260c6ec.jpg)

辭源正編 (1915):
![辭源正編 (1915)](https://user-images.githubusercontent.com/8684843/188047944-6db51d03-37a4-408a-89df-13d6ae7461ac.jpg)

商務印書館萬有文庫 四庫全書總目提要 (1931):
![四庫全書總目提要 (1931)](https://user-images.githubusercontent.com/8684843/188049000-30d62b30-fbad-468f-801d-ee5e8a69d021.png)

參見 U+022ff3 "𢿳"
![U+022ff3 "𢿳"](https://user-images.githubusercontent.com/8684843/188049502-b85e7082-3e05-4f43-8a2c-3cbe751ac57d.png)

**Comment by mondain-dev** [comment]
辭源字頭從「龴」，正文字形從「匚」

**Comment by i-font** [comment]
感謝提問。原則上應依《檢校表》所述，選擇「龴」形。「𢿳」字是因爲確實罕用，我們的工作人員尚未檢校修訂之。其實它不但左邊沒依《檢校表》，其右邊也從「攵」變成「攴」，而「𢿢」是獲編進另一Unicode碼位的字元。我們將會在下一版本修正這字元。
