### ISSUE TITLE
關於良部件（在左）

### ISSUE THREAD

**Issue by haydenwong7bm** [ichitenfont/inheritedglyphs#28]
本人認爲，良末兩筆不論變或不變作頓點，皆可接受，一樣符合字理。
<img width="434" alt="image" src="https://user-images.githubusercontent.com/51369959/188940515-f9bfa8c4-52b0-4bcd-aa11-285ca0b950d1.png">
![康煕字典字頭郞](https://user-images.githubusercontent.com/51369959/188939225-6f52b1a6-537b-42e3-92a9-cb8b48afbff3.png)
![康煕字典字頭朗](https://user-images.githubusercontent.com/51369959/188939254-62aaba70-b61c-4d8f-994a-2266b9078756.png)
[香港元朗路牌](https://www.instagram.com/p/Cf5hcWLvFKM/)

**Comment by i-font** [comment]
感謝意見。這部件我們之前的內部討論已處理了。請期待本月的大更新！😁

**Comment by SyaoranHinata** [comment]
![image](https://user-images.githubusercontent.com/8178284/190866518-6a175630-7286-4a97-9858-9f7eadc69071.png)
