### ISSUE TITLE
《检校表》 臿部件 内容有问题

### ISSUE THREAD

**Issue by ghost** [ichitenfont/inheritedglyphs#29]
《检校表》 臿部件 内容有问题
![未标题-1](https://user-images.githubusercontent.com/113996166/191269758-5455a13d-6946-44f4-a452-18a0e3884336.jpg)

能不能改正一下吗？谢谢！

**Comment by i-font** [comment]
抱歉，文件的示範字型遺失了，應該是這樣：
![圖片](https://user-images.githubusercontent.com/24702034/191360136-7ff1d7d4-e30f-4192-b835-50b8e641abfe.png)

我們會在日後的版本修正。
