### ISSUE TITLE
关于 含有"⺕"的部件的内容问题

### ISSUE THREAD

**Issue by xiatisn** [ichitenfont/inheritedglyphs#30]
关于 含有"⺕"的部件的内容问题(不是"彑"和"彔“部件)
看下图
![未标题-1](https://user-images.githubusercontent.com/113996166/192097867-a16f502b-9170-4d3b-b81b-cbe5a05c173a.jpg)

如果可以的话，建议将不作的部件改回原来的"𫜹“(就是"彐”底部一横笔不出脚)。

**Comment by i-font** [comment]
感謝回報，我們將在下一版本更正。
