### ISSUE TITLE
关于”往“部件内容问题

### ISSUE THREAD

**Issue by ghost** [ichitenfont/inheritedglyphs#31]
看下图
![2](https://user-images.githubusercontent.com/113996166/192100947-4e07904b-f398-4990-bc03-dfadb6293b93.jpg)

这看起来不觉得奇怪吗，如果能的话，建议您把我画红线的地方修改一下。

**Comment by i-font** [comment]
寫得簡略了點兒。改作『「之」省略下方作「亠」形，「王」省略上方作「土」形』吧。

**Comment by xiatisn** [comment]
不是这个意思，我想说的是这明明是上从"之"省，下从"王"省，为什么是"「之」省下作「亠」，「王」省上作「土」形"这种说法？

**Comment by xiatisn** [comment]
我只是告訴您將我畫紅綫的地方修改掉，其他的還是得保留。

**Comment by xiatisn** [comment]
> 寫得簡略了點兒。改作『「之」省略下方作「亠」形，「王」省略上方作「土」形』吧。

不是，有問題的是畫紅綫的地方，是這應該是“上從‘之’省，下從‘王’省”，爲什麽是"「之」省下作「亠」，「王」省上作「土」形"這種說法？
這就是我覺得奇怪的理由，其他的沒什麼問題。

**Comment by xiatisn** [comment]
你只要把我畫紅綫的地方修改一下就可以了，其他的就留下來。
