### ISSUE TITLE
Inconsistent shape of 禸

### ISSUE THREAD

**Issue by epistularum** [ichitenfont/inheritedglyphs#37]
The inherited glyphs document lists two shapes for this component, one with the middle component looking like ム and another shape where the first stroke is broken and vertical, forming a right angle with the next stroke when combined with a stroke coming from a component above.

Wouldn't it be better to unify the look and only have the straight variant?
![image](https://user-images.githubusercontent.com/34507493/234199855-5b286565-4fbb-4c0f-b7f2-801804df0a31.png)

**Comment by i-font** [comment]
First of all, "禸" is not an independent character, as it has not been found in unearthed documents, nor has been used alone in later times. It evolved from the lower part of the characters "萬", "禽", "禹", "离" etc., which had a straight stroke followed by an oblique or hook-like stroke. Later, people added a horizontal decorative stroke on it, which gradually developed into the shape like "九". Written in the form of "Stroke TU" is slightly more consistent with the ancient stroke than broken into "Stroke V" and "Stroke U".

Secondly, we have consulted with Chinese character designers and calligraphic teachers, and they pointed out that it is easier to balance the whole Chinese character with the stroke slanted to the left. Unless the stroke goes all the way down from the top like the "禺" shape, there is no need to tilt it midway. This is consistent with our sampling results. Therefore, we also respect the normality of the existing forms.

**Comment by epistularum** [comment]
I understand the reasoning, it makes a lot of a sense design wise. Most dictionaries list the ム shape as being 3 strokes so I assumed that the broken version seen in 萬 was more correct since it's written with 3 strokes whilst ム is often written as 2.
