### ISSUE TITLE
排版小建議：將行長設置為字號的整數倍

### ISSUE THREAD

**Issue by RuixiZhang42** [ichitenfont/inheritedglyphs#4]
參考資料：[Type is Beautiful — 从「行长为字号的整数倍」说起](https://thetype.com/2017/07/12513/)

《傳承字形部件檢校表》與《傳承字形筆畫表》內容豐富，在排版上能否更加精緻一些？目前的行長似乎比 34 個漢字稍微長一點點，導致每一個自然段的最後一行都有「錯位」的現象：

> ![inheritedglyphs](https://user-images.githubusercontent.com/39968857/56594359-ae0e3580-65ba-11e9-82d0-8cc20974ceeb.png)
>《傳承字形部件檢校表》1.20 版本，頁&nbsp;2。

> ![inheritedglyphs_stroke](https://user-images.githubusercontent.com/39968857/56594544-09402800-65bb-11e9-8251-c3b71fec0cef.png)
> 《傳承字形筆畫表》1.20 版本，頁&nbsp;1。

以 Adobe 軟件或是 MS Word 為例，若內文用五號字（10.5&nbsp;磅）、每行 34 個漢字，那麼版心寬度應該為 10.5×34 = 357&nbsp;磅 = 4.958333&nbsp;英吋 = 12.594167&nbsp;釐米。

**Comment by SyaoranHinata** [comment]
這些文件，我們只是以文書程式來編撰，並非像Type is Beautiful那篇文章所述般使用高階排版軟件。文件裏有許多特殊字元甚或圖形，它們本身所佔寬度也不易調節。若固定每行漢字數目，又會有無法避頭標點的問題。而且這並不是本系列文件的重點，與本系列文件的作用無關。
