### ISSUE TITLE
《传承字形部件检校表》關於「非」

### ISSUE THREAD

**Issue by treemoons** [ichitenfont/inheritedglyphs#40]
關於「非」部件的不同意見。
「非」做傳承部件應爲對稱。首筆不應爲豎撇，最後也不爲提點。

箇人認爲非對稱字形的「非」是手寫字形，而不是傳承字。單字可採用，但作爲部件不應該對本字做過多修飾。參考「丹」的單字與部件。

箇人否認美觀傾向手寫，如「排，悲，輩」，特別是「輩」，對稱字的部分傾斜導致字體偏倒的不協調感官。

**Comment by i-font** [comment]
您好！感謝您的意見。在字理上，「非」字本爲兩形相背。或謂二人相背形，上各添一筆與「北」字區分；或謂兩翼相背形。此字字形歷代變化甚烈。按商甲骨文較像是二人相背者。西周金文已出現與商甲骨文差異頗大的字形，相背兩者的頂橫下移，以致看上來較象兩翼相背。在《說文》小篆中，下方還凸出來。隸變後，今天楷書字形已跟原形相距甚遠。它的原始字理不太容易彰顯出來，只是兩者相背的形狀還是可以看到。不過，無論左豎是寫得筆直，還是寫成豎撇，基本上都看到它是左右相背對稱的。

在這種情況下，我們尊重約定俗成的今形，基本上以明體的取樣結果爲準。而取樣的結果，發現左豎作豎撇形者爲大宗，因此我們就直接沿用之。其實，明體儘管不是楷體，但它也有明體造型上的美觀需求。除了「非」字，明體尚有不少字，是把相鄰兩豎中的左豎作豎撇的，例如「介、丌、亦、井、开、幵、并、川」等諸部件，在明體裏，不論獨用還是作偏旁，其左豎基本上都作豎撇。對於這種情況，我們分析後都認爲它不影響字理，就尊重今天的取樣結果。

希望能回答到閣下的疑問。謝謝！
