### ISSUE TITLE
未在《傳承字形部件檢校表》找到「示」 部件（在下）

### ISSUE THREAD

**Issue by treemoons** [ichitenfont/inheritedglyphs#45]
翻閱文件只找到「示」 部件（在左）的記錄，並沒有在下部的，如：禁，禦，票等。
而查看到I.Ming體的字形中，發現I.Ming明體中皆顯示爲「二小」，而非「一𥘅」，異於「示」 部件（在左）。

希望能在部件檢索表中做出規定統一部件。也希望能在後期的一點字體中遵循此規定。

抱歉，提出此要求。

**Comment by SyaoranHinata** [comment]
謝謝閣下的意見。

「示」字的字理是神主牌的象形，原始時作「T」形，後來上、左、右也加上筆畫。

「示部件」居左時，有「⺬」與「ネ」兩種字形。作「ネ」形者跟歷來演變的字形相差甚遠，只是手寫時方便一點而已，因此我們按傳承字形的取樣結果，規定應作符合歷代形變的「⺬」。

「示部件」居下時，其實「⿱二小」之形與「⿱一𥘅」之形，於彰顯字理功能上相差不遠，大體都能看到以「T」形爲核心添筆。然而「⿱一𥘅」之形是頗違反明體、黑體等印刷字形習慣的，我們的採樣中，傳承字形是百分百作「⿱二小」之形，並無爭議，沒有甚麼要特別說明，因此我們也沒有特別敘述，沒有爲之立下條目。
