### ISSUE TITLE
對「無」字字形的詢叩

### ISSUE THREAD

**Issue by qz-i** [ichitenfont/inheritedglyphs#47]
我注意到在「傳承字形推薦形體表」的 60／315 頁，U+7121 _(統一碼)_ ，HB1-B54C _(Big-5, Level1; 大五碼 常用字)_ 上的「無」字，以第二筆橫爲長。

而這是完全不符合傳承字形標準的。

可以設想，制定標準者必然是受到了 J _(日本)_ 標的影響，以致做出了錯誤的判斷。

不過，第一願賢知注意， J 標是最近 40 年閒才改的。鉛字時代日本的字模，幾乎不見第 2 筆橫比第 3 筆橫更長的字模出現 _（若缺少相關資料，儘先覈査時日本以爲漢字標准的《當用漢字表》）_ 。至於其他地區，此種鉛字形，乃可謂未所聞者 _（若實有，叨承舉之證）_ 。

第二願賢知注意，目前賢知應當傳承的，或以爲主要參考的宋以後印刷字體，「無」字亦均作第 3 筆橫更長。 _（可儘先見《廣韻》《增韻》《洪武正韻》《康熙字典》等；若實有，叨承舉之證）_

第三願賢知注意，目前僅有 J 標做了修改。目前統一碼聯盟收録 _（此處不是誤用，謹從《廣韻》）_ 的七種標準 _(即G, HB, T, J, K, V, KP)_ ，包括手寫標準以及印刷標準，其中只有日本標準采用了第二畫橫較長的處理。

第四願賢知注意，從字理和字形發展的角度上，和歷代手寫書體的演變上，也是第二畫橫更長占優勢。
「無」字早期的演變儘先參考[這帙回答](zhihu.com/answer/1668834563)：

 _下面勘對『字統網』給出的字形庫，使用了數張圖片：感謝。_ 

後來，無字從回答中的樣子演變成了以下的形式（也即把中央的類「人」形省略的簡體）。

![無的演變](https://github.com/ichitenfont/inheritedglyphs/assets/110292700/e7988960-ad6b-4433-8282-c8a8ab8422ed)

![無的演變](https://github.com/ichitenfont/inheritedglyphs/assets/110292700/7aa01ccb-e2cb-45ae-9bba-e67897345a46)

這裏需要注意的是，在目前可見的全部金文、簡帛中，由於上方的（由一橫演變而來的）兩橫象人兩臂，歷來長度均是一樣長的。

到了漢代，發生了漢字的隸變；這字形演變至唐，形成了確定的楷書書體。關於這段時間「無」的寫法，儘先看下面一張圖給出的大量圖例。

![無的演變](https://github.com/ichitenfont/inheritedglyphs/assets/110292700/5f81d791-5c7a-4afc-8660-136abf08c0f6)

可以看出，無論是第三筆橫過分長的寫法，還是第三筆橫和第二筆橫幾乎等長的寫法，被嚴苛遵守的是首兩筆等長的繩墨。而第三筆橫較長的寫法在魏晉以後佔據了主流。這説明，在形成印刷字體的唐宋之際，確鑿第三筆橫遠遠長的寫法爲主流。

的確有一種異議是「鬼」「卑」「彔」「彖」「虜」「者」「辶」等字的「正字」都誕生在宋明清之際，於是唐宋的印刷體不能作爲證據這樣的論調；還有一種異議是漢字要吸取民間書體的發展，隨之而變化。則先不論「正字」究竟正不正，「變化」究竟對不對。但是僅僅關於「無」字，並不存在這樣的事。

![無的演變](https://github.com/ichitenfont/inheritedglyphs/assets/110292700/129b6cb3-457a-4c59-b117-e7216a2e1361)

以上給出的是字統網上記載的宋以降「無」字的部分書體。可以看出，基本完全繼承了魏晉后一貫的寫法，並不存在一些矯枉。

現代的「無」字書體，默認應使第一筆橫較短的前提下，隨之必然要使第二筆橫亦較短；此時必然令第三筆橫最長。這也是最符合「傳承字形」所謂「傳承」的上儀。

以下是 zh.wikisource.org (維基文庫)上給出的一個紅樓夢刻本的「無」字寫法。此一并列出，以孚眾焉。

![image](https://github.com/ichitenfont/inheritedglyphs/assets/110292700/4931047e-24cc-421f-b451-d10ee1fc5696)

另外有四个版本，亦列于下；用於補充上圖清代楷書太少的缺憾。

![image](https://github.com/ichitenfont/inheritedglyphs/assets/110292700/13e34ee1-c2f1-46cd-9b8e-c62a5340c04f)
![image](https://github.com/ichitenfont/inheritedglyphs/assets/110292700/408b6338-3b48-4bea-8757-cb5ead0802a3)
![image](https://github.com/ichitenfont/inheritedglyphs/assets/110292700/f88612c5-46eb-4387-a318-1f4ca744efde)
![image](https://github.com/ichitenfont/inheritedglyphs/assets/110292700/5563775d-d266-49cf-9c09-719ab77dcd53)

綜上，我們可以實證，無第二筆長是一個譌寫；是一个無論從習慣、經驗或字源角度都毫無道理的剌謬，是一個在進入 Digital Age 才出現的錯誤。如果要猜測原因，或許有日本年青人普遍認爲「無」的第三筆是竪這方面的聯係，此處不再贅述。

手稟不虔，若拙筆遲想，還請見諒。不文願有濟於事，且期隱栝。

**Comment by i-font** [comment]
您好！感謝您的意見。在字理上，「無」字本爲「舞」的初文，从「大」（正面人形），張開的雙臂下拿着跳舞用的道具（似是牛尾或草木製的飾物）。隸變後，整個字遭整體融合，「大」形僅見頂部的「𠂉」筆畫，其餘部份與跳舞道具融和一體，已再看不出來。

因此，無論下方的兩橫，哪筆長，哪筆短，其實並無影響字理，依然是不容易彰顯出來，必須追溯篆前文字才可明白。這情況在字理上，談不上是「對」或「錯」、孰「優」孰「劣」，無法判斷何者爲「正」、何者爲「訛寫」的。只能尊重約定俗成的今形。

至於今形的判斷，標準化文件是以明體爲準，且面對的是現代排印之需求。對於明體字，我們只以本身爲明體的文本來取樣，尤其是今天的現代明體，避免「認楷作母」。楷體字跟明體字不是完全無關，但我們應該尊重明體本身的需求，否則盲目要求明體甚麼都與楷體一致，只會變成臺灣敎育字樣那種毀掉明體的標準。楷體的情況，可以參考，但不應完全直接套用在明體或現代排印字型上。閣下在本帖上所擧之例，大多爲楷體，或涉隸書，請恕這方面不太符合我們的取樣繩尺。而我們的採樣範圍中，似乎是中橫略長的比下橫略長的多，因爲它沒有影響字理，我們也直接從之。

當然，我們也知道在楷體中，下橫略長的字形比較多，因此我們在同系列的《筆畫表》中，已說明「明楷之間，筆畫長短不同，有時並不對立」，擧例中也有「無」字。我們絕對沒有認爲要排斥下橫最長的字形，是一同接納的。甚至對於明體，這方面我們也沒有特別要求，在《檢校表》中並沒指定「無部件」要中橫還是下橫最長，因爲實在不影響字理。只是在《推薦形體表》中，每字必須列出一體，我們就尊重今天的取樣結果而已。要是字型設計者製作成下橫最長者，我們對此字形亦無異議。

希望能回答到閣下的疑問。謝謝！

**Comment by qz-i** [comment]
@i-font

感謝回覆。

可以的話還是希望給出一些圖例爲佳。
