### ISSUE TITLE
“華”的最下横與次下横長短

### ISSUE THREAD

**Issue by garfieldLSY** [ichitenfont/inheritedglyphs#48]
“華”在大陸、日本、朝鮮半島地區最下横更長，但是在港臺次下横更長，然而檢校表裏没有明確規定哪個更加合理。

**Comment by SyaoranHinata** [comment]
感謝閣下的意見。

「華」字於字理而言，中間像花朵盛放之形，下像莖葉。又會聲化作形近的「于」，使之變成形聲字。

今天明體等印刷字形並沒有作「于」形者，因此我們衡量下，只看像莖葉之形。如是者，哪橫更長，對莖葉之象形的反映並無甚麼影響，很難說哪個更合理，因此我們目前也沒有硬性規定。

**Comment by garfieldLSY** [comment]
好的，感謝您的答復。
