### ISSUE TITLE
關於“𠫓”部件

### ISSUE THREAD

**Issue by GreenYun** [ichitenfont/inheritedglyphs#5]
在《傳承字形部件檢校表》頁70中的第一部件字“�”按《說文解字》應爲第一筆與第三筆相連的“𠫓”，考証：http://www.zdic.net/z/21/sw/80B2.htm 而按照該頁面中“毓”為“育”同源字，部件也相同，而在《康熙字典》“𡿮”字的註解（ http://www.zdic.net/z/8c/kx/21FEE.htm ）中，也說明部件應爲“𠫓”字。
兹認爲該部件的確定需要斟酌。

**Comment by SyaoranHinata** [comment]
頁70的第一部件就是「𠫓（U+20AD3）」，「育、毓、㐬（𡿮）、充」諸字皆從「𠫓」。《檢校表》裏的「𠫓」字和「𠫓部件」一律作四筆。

我們知道，甲金篆文裏，包括《說文解字》的小篆字頭，「𠫓」字即是倒轉的「子」字。

然而，楷書筆畫與古文不同。古文的線條圓滑多變，可隨意詰屈；楷書卻必須分解作若干指定的筆畫，這些筆畫相對古文的線條都明顯較短和較直，要是屈曲就通常會起角。因此，按《說文解字》的篆字，根本不可能得出在楷書裏「應爲第一筆與第三筆相連」這結果。而且這個倒「子」字，無論在楷書裏怎麼寫，都不可能眞的寫成倒「子」之形。

「𠫓」字寫成四筆還是三筆，都不會跟其他部件相混，不會損害字理。然而，只要思考得闊一些，便可知道取四筆者比取三筆者佳。一來，四筆的寫法符合歷史習慣，古人無論書法還是彫板，絕大部份都作四筆之形——包括閣下擧出《康熙字典》裏的「𡿮」字字頭，其上方也明顯刻作四筆。二來，與三筆的寫法相比，四筆的寫法較像「⿻𠄏一」這個倒「子」之形；若勉強寫作三筆，反而跟倒「子」之形相差更遠。三來，寫作四筆的「𠫓」是我們的取樣來源裏最常見、最普遍的形體。

因此，我們有理由要捨近就遠，不取四筆的「𠫓」，改作三筆嗎？

**Comment by hfhchan** [comment]
隸變以來很多篆文作一筆的筆畫，會因應方便書寫而斷開。比如説，「方」字頭頂篆文裏查實與下方橫折鈎是一筆，書法常常將「方」寫如「才」，反可謂較接近原本的寫法。

傳承字形重點在於傳承，歷史下演變出來的形態中，選較符合字理的一個。近代出於意識形態需要而新造的寫法，尤其係漠視隸變定局或者有違明體風格者，一般不採用。

**Comment by i-font** [comment]
附上樓主談及的「育、毓、𡿮」三字，在樓主提供的「漢典網站」連結裏的《康熙字典》字樣擷圖，以及香港中文大學掃瞄同文書局版《康熙字典》的字樣擷圖。字樣中的「𠫓部件」，到底是作四筆的寫法，還是三筆的寫法，應當相當清晰，毋庸爭議。
![圖片](https://user-images.githubusercontent.com/24702034/69004022-18b40380-0947-11ea-972b-8125e56983d9.png)
