### ISSUE TITLE
對「粵」部件的疑問

### ISSUE THREAD

**Issue by VentusUta** [ichitenfont/inheritedglyphs#57]
據《檢校表》，「粵」上方從「⿵𰃦釆」：

![image](https://github.com/user-attachments/assets/b1ebe3a1-8055-46e1-95ff-ae669344f095)

但該字疑似是小篆訛變字形？其似乎本應作「粤」（上方爲「⿱丿𭁨」，即「雨」的變體）：

![image](https://github.com/user-attachments/assets/21b13756-98b6-4a8a-9b2e-6ac411a6335f)

（《字源》）

且在《廣韻》《康熙字典》等古代字書中也作「粤」（上作「⿱丿𭁨」）的字形（列在「米」部），《大漢和辞典》亦作「粤」:

- ![image](https://github.com/user-attachments/assets/674c7984-637f-4bb0-9d11-206fe5d7330b)
（《廣韻》）
- ![image](https://github.com/user-attachments/assets/ef5ce1e2-765c-4d4e-8c01-a86e2097490f)
（《康熙字典》，列在「米」部）
- ![image](https://github.com/user-attachments/assets/bcc50f0c-8430-420c-b76a-f6b7780d9814)
（《大漢和辞典》，列在「米」部）

請問是否是我搞錯了什麼？

還請不吝赐敎，非常感謝。

**Comment by SyaoranHinata** [comment]
感謝您的意見。

漢字的變化發展了數千年，有些字形，從先秦初始形態至今，經過多次曲折的演變，已難以看到初形。

就例如閣下提出的「粵」字，即使有學者指其上方本爲「雨」，但現今我們若寫成「雩」，絕大多數人看到後都不以爲這是「粵」字（註1）。同時間，無論寫作「⿵𰃦米」（即「宩」）或「⿵𰃦釆」（即「宷」），絕大多數人都不會理解爲「雨」的變體。這樣的字形，已無法從直觀上與其初形勾連。

如是者，我們並不強行攀附先秦初形，而會視其爲已脫離初形的變化。已脫離初形的變化，粗略來說可分爲兩種，一種是訛變，一種是理據重構。詳見王寧《漢字構形學講座》。若有字形能滿足理據重構的條件，使其不致於落入無義可從的訛變之中，我們會盡量推薦滿足理據重構條件的字形。

「粵」字的兩種寫法，若採用「⿵𰃦釆」（「宷」）形，正好能滿足理據重構的條件。相反，若採用「⿵𰃦米」（「宩」）形，我們只能視其爲已訛變。

而抽離「粵」字，縱看「米」和「釆」兩部件，在隸變中混同嚴重，後來明體的定形，還是參照字義，花了一番工夫去再劃分的。

然而，在這番再劃分時，「粵」字在一些重要字書中遺漏了，仍然作从「米」之形，包括《康熙》及其後繼的《大漢和》皆是，主因是梅膺祚的《字彙》。梅氏將其放進「米」部，以爲《說文》的字形就是「从宩，从亏」，以爲「宩」是古「審」字。其實他對構字的理解，與《說文》這種「从宷，从亏」的看法沒分別。關鍵是他把《說文》的「宷」字寫成「宩」，沒注意「宷」字字形中「从釆」與「从米」的分辨。

![image](https://github.com/user-attachments/assets/05258eb7-9b94-40d5-80c7-784c8dafbbd0)

《字彙》是首本把部首重設作214部的字書。在《字彙》之後，繼承它的字書，包括《正字通》、《康熙》、《大漢和》，基本上都依其歸部，甚至在字頭選形上會刻意配合其歸部（註2）。這種盲從，令這幾部後繼字書都沒有把「粵」的脫隊問題修正。

不過，在重新劃分好「米」或「釆」之別的楷書中，古「審」字定形作「宷」，而「宩」是「屎」的異體。這個「宩」字作爲「屎」的異體，古人也罕用，所以忽略了這點並不爲奇。但今人已重視了，多年前還有家長不滿算命師推薦初生女兒起名用「宩」字（即「屎」字）而鬧上新聞。我們面對今天的需求，實在不能不正視，不能繼續因循隸變後「宷、宩」不分的漏洞。

而且客觀來說，在我們的採樣結果，以及比對今天電腦字型字形的結果，从「釆」的「粵」字並非少數，結果是多的。

![image](https://github.com/user-attachments/assets/e38111f8-77e5-42a3-a136-f722405aa46a)

綜合上述考慮，我們硏訂《檢校表》時，以从「釆」的「粵」爲推薦字形。

希望能解答到閣下的提問，謝謝！

註1：中文大學《漢語多功能字庫》仍分爲兩個字頭：
https://humanum.arts.cuhk.edu.hk/Lexis/lexi-mf/search.php?word=粵
https://humanum.arts.cuhk.edu.hk/Lexis/lexi-mf/search.php?word=雩

註2：比如「最」字，上方明明从帽子的「⺜」，不从子曰的「曰」。但《字彙》爲檢索方便放進「曰部」，字頭仍採用从「⺜」之形。《康熙》不但盲從《字彙》的歸部，還爲了配合此歸部，把字形改作「从曰，从取」之形，「曰」的左上角還特地留下缺口——這是《康熙》強調「曰」字的特色。

P.S.《廣韻》或其他非明體古書的字形，並不在我們的取樣範圍，只是參考材料之一。

**Comment by VentusUta** [comment]
原來是這樣，非常感謝您的解惑。

**Comment by aikahiiragi** [comment]
看到截圖畫面「花錢求助命理師，取名古字變成屎」笑鼠了，還押韻耶
