### ISSUE TITLE
《传承字形笔画表》中“小木”笔误

### ISSUE THREAD

**Issue by FListLee** [ichitenfont/inheritedglyphs#6]
![image](https://user-images.githubusercontent.com/34062491/62868661-ba282980-bd48-11e9-9866-ad48d29e787b.png)
第二行的“小木”当有勾

**Comment by FListLee** [comment]
P22

**Comment by SyaoranHinata** [comment]
感謝賜正！我們已在第1.22版（checklist_of_inheritedglyphs_stroke-1.22.pdf）裏更正。
