### ISSUE TITLE
《传承字形部件检校表》“冊部件”笔误

### ISSUE THREAD

**Issue by FListLee** [ichitenfont/inheritedglyphs#7]
P64，冊部件不作册，但姗字笔误
![image](https://user-images.githubusercontent.com/34062491/63028569-a7952800-bee1-11e9-9433-e9d2e16f88c9.png)

**Comment by i-font** [comment]
感謝回報^O^♥！已於1.31版（checklist_of_inheritedglyphs-1.31.pdf）裏修正。
