### ISSUE TITLE
頁眉與頁腳改為宋體

### ISSUE THREAD

**Issue by sgalal** [ichitenfont/inheritedglyphs#8]
<div lang="zh-HK">

當前版本中頁眉與頁腳為黑體，尤其是數字為黑體較為不美觀。

</div>

**Comment by SyaoranHinata** [comment]
閣下說的宋體應該指明體而非仿宋體對吧？
可是內文全都是明體，一般的排版習慣上，頁眉頁腳會替換作黑體，以作區別，讓讀者看得比較清晰啊。

**Comment by aikahiiragi** [comment]
我是負責協助排版的佟藍歌。
想說那個黑體 ( 包括數字 ) 是「游ゴシック」( Yu Gothic ) ，是許多設計師都認同的最美黑體。

**Comment by sgalal** [comment]
@aikahiiragi 我正是覺得 Yu Gothic 的數字與正文的明體不協調，不過看來只是我的個人意見，所以不再提出異議。
