### ISSUE TITLE
請求《傳承字形推薦形體表》中的字符總表

### ISSUE THREAD

**Issue by sgalal** [ichitenfont/inheritedglyphs#9]
最近我正在依照《傳承字形推薦形體表》進行學習，我希望能有一個《傳承字形推薦形體表》中的字符總表（文字檔），這樣我可以製作爲網頁，便於我學習時檢索

**Comment by SyaoranHinata** [comment]
這個就暫時非官方私下給予吧：
http://input.foruto.com/ccc/1.font/font/raw/checklist_of_inheritedglyphs_recom-1.02_a.docx
http://input.foruto.com/ccc/1.font/font/raw/checklist_of_inheritedglyphs_recom-1.02_b.docx
http://input.foruto.com/ccc/1.font/font/raw/checklist_of_inheritedglyphs_recom-1.02_c.docx
